FROM debian:9.4 as builder

WORKDIR /

COPY homefs.tar.gz /

RUN mkdir -p /homefs && \
    cd /homefs && \
    tar -xvpzf /homefs.tar.gz --numeric-owner


FROM debian:9.4


LABEL \
    com.github.lnls-sirius.license="GPLv3" \
    com.github.lnls-sirius.docker.dockerfile="Dockerfile" \
    com.github.lnls-sirius.vcs-type="Git" \
    com.github.lnls-sirius.vcs-url="https://github.com/lnls-sirius/docker-debian9-homefs.git" \
    maintainer="Lucas Russo"

COPY --from=builder /homefs /homefs
