FROM debian:9.4 as builder

WORKDIR /

COPY rootfs.tar.gz /

RUN mkdir -p /rootfs && \
    cd /rootfs && \
    tar -xvpzf /rootfs.tar.gz --numeric-owner

FROM debian:9.4

LABEL \
    com.github.lnls-sirius.license="GPLv3" \
    com.github.lnls-sirius.docker.dockerfile="Dockerfile" \
    com.github.lnls-sirius.vcs-type="Git" \
    com.github.lnls-sirius.vcs-url="https://github.com/lnls-sirius/docker-debian9-rootfs.git" \
    maintainer="Lucas Russo"

COPY --from=builder /rootfs /rootfs
